backend:
  name: git-gateway

collections: 
  - name: "services"
    label: "Services"
    folder: "views/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/simple.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Icon Name", name: "faIcon", widget: "string"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "services"}

media_folder: "assets/images" # Media files will be stored in the repo under static/images/uploads
